### ISSUE TITLE
menu search problem in light mode

### ISSUE THREAD

**Issue by hanndoddi** [fablabisastaff/fabisa_site#18]
menu has a search problem could be same fix as with the nav problem.

**Comment by hanndoddi** [comment]
change color in line 2259 in home.html to grey

```css
/* Section/Article */
	
	section.special, article.special {
			text-align: center;
		}
	
		header p {
			color: rgb(126 126 126);
			position: relative;
			top: -0.25em;
		}
```
